- name: (Re)start server
  ansible.builtin.debug:
    msg: "Restarting server"
  changed_when: true
  notify:
  - stop_server
  - wait_server_stop
  - start_server

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Wait for server listening
  ansible.builtin.wait_for:
    port: 25565
    delay: 10
  retries: 3
  delay: 30
